-- PostgreSQL schema for the browser-based Dayora application. Monetary values use paise.
CREATE TABLE IF NOT EXISTS users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL, full_name TEXT NOT NULL, email TEXT NOT NULL,
            department TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'EMPLOYEE',
            employee_code TEXT, employment_type TEXT NOT NULL DEFAULT 'Permanent',
            annual_balance BIGINT NOT NULL DEFAULT 18, sick_balance BIGINT NOT NULL DEFAULT 10,
            casual_balance BIGINT NOT NULL DEFAULT 8, active BIGINT NOT NULL DEFAULT 1
        );
        CREATE TABLE IF NOT EXISTS leave_requests (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, employee_id BIGINT NOT NULL,
            leave_type TEXT NOT NULL, start_date TEXT NOT NULL, end_date TEXT NOT NULL,
            days BIGINT NOT NULL, reason TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'PENDING',
            admin_comment TEXT DEFAULT '', created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
            decided_at TEXT, FOREIGN KEY(employee_id) REFERENCES users(id)
        );
        CREATE TABLE IF NOT EXISTS notifications (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, message TEXT NOT NULL,
            is_read BIGINT NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
            FOREIGN KEY(user_id) REFERENCES users(id)
        );
        CREATE TABLE IF NOT EXISTS tasks (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            employee_id BIGINT NOT NULL REFERENCES users(id),
            assigned_by BIGINT NOT NULL REFERENCES users(id),
            title TEXT NOT NULL, instructions TEXT NOT NULL, due_date TEXT,
            duration_minutes BIGINT NOT NULL DEFAULT 60 CHECK(duration_minutes BETWEEN 15 AND 60000),
            status TEXT NOT NULL DEFAULT 'TODO' CHECK(status IN ('TODO','IN_PROGRESS','COMPLETED')),
            created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
            updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
        );
        CREATE INDEX IF NOT EXISTS idx_tasks_employee ON tasks(employee_id);
        CREATE TABLE IF NOT EXISTS personal_checklist (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            employee_id BIGINT NOT NULL REFERENCES users(id),
            title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 160),
            completed BIGINT NOT NULL DEFAULT 0 CHECK(completed IN (0,1)),
            created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
        );
        CREATE INDEX IF NOT EXISTS idx_checklist_employee ON personal_checklist(employee_id);
        CREATE TABLE IF NOT EXISTS conversations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            employee_id BIGINT NOT NULL REFERENCES users(id),
            subject TEXT NOT NULL, topic TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
        );
        CREATE INDEX IF NOT EXISTS idx_conversations_employee ON conversations(employee_id);
        CREATE TABLE IF NOT EXISTS conversation_messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            conversation_id BIGINT NOT NULL REFERENCES conversations(id),
            sender_id BIGINT NOT NULL REFERENCES users(id),
            body TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
        );
        CREATE INDEX IF NOT EXISTS idx_conversation_messages_thread ON conversation_messages(conversation_id, id);
        CREATE TABLE IF NOT EXISTS attendance (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            employee_id BIGINT NOT NULL,
            attendance_date TEXT NOT NULL,
            check_in TEXT NOT NULL,
            check_out TEXT,
            status TEXT NOT NULL DEFAULT 'PRESENT',
            UNIQUE(employee_id, attendance_date),
            FOREIGN KEY(employee_id) REFERENCES users(id)
        );
        CREATE TABLE IF NOT EXISTS work_schedule (
            weekday BIGINT PRIMARY KEY,
            day_name TEXT NOT NULL,
            start_time TEXT,
            end_time TEXT,
            is_working_day BIGINT NOT NULL DEFAULT 1
        );
        CREATE TABLE IF NOT EXISTS salary_records (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            employee_id BIGINT NOT NULL REFERENCES users(id),
            salary_month TEXT NOT NULL,
            basic_pay BIGINT NOT NULL CHECK(basic_pay BETWEEN 0 AND 9999999999),
            allowances BIGINT NOT NULL DEFAULT 0 CHECK(allowances BETWEEN 0 AND 9999999999),
            deductions BIGINT NOT NULL DEFAULT 0 CHECK(deductions BETWEEN 0 AND 9999999999),
            status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','PAID')),
            paid_on TEXT,
            notes TEXT NOT NULL DEFAULT '',
            updated_by BIGINT NOT NULL REFERENCES users(id),
            created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
            updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
            UNIQUE(employee_id, salary_month),
            CHECK(deductions <= basic_pay + allowances),
            CHECK((status='PENDING' AND paid_on IS NULL) OR (status='PAID' AND paid_on IS NOT NULL))
        );
        CREATE TABLE IF NOT EXISTS department_salary_defaults (
            department TEXT PRIMARY KEY,
            basic_pay BIGINT NOT NULL CHECK(basic_pay BETWEEN 1 AND 9999999999),
            updated_by BIGINT REFERENCES users(id),
            updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
        );

CREATE TABLE IF NOT EXISTS admin_reminder_settings (
            admin_id BIGINT PRIMARY KEY REFERENCES users(id),
            salary_day BIGINT NOT NULL DEFAULT 1 CHECK(salary_day BETWEEN 1 AND 31)
        );
        CREATE TABLE IF NOT EXISTS admin_reminder_reviews (
            admin_id BIGINT NOT NULL REFERENCES users(id),
            kind TEXT NOT NULL CHECK(kind IN ('attendance','tasks','salary')),
            period TEXT NOT NULL, reviewed_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
            PRIMARY KEY(admin_id,kind,period)
        );

CREATE TABLE IF NOT EXISTS app_migrations (
            name TEXT PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
        );

CREATE UNIQUE INDEX IF NOT EXISTS idx_employee_code ON users(employee_code) WHERE role='EMPLOYEE' AND employee_code IS NOT NULL;
